version: '2'
services:
  app:
    build: .
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      PORT: 3000
      DB_CONNECT: db/api_a
  db:
    image: mongo
